### ISSUE TITLE
[Docs] [chore] Create documentation on programmableweb alturnative

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#278]
# Description

[Programableweb](https://en.wikipedia.org/wiki/ProgrammableWeb) no longer exists as of Feb 2023, We previously had a lot of exposure from their listing as a learning resource, and would like to document the free api on other platforms. [rapidapi](https://rapidapi.com) is a robust platform which has a lot of good free resources for small teams, it also gets people started using the api with code snippets and allows for people to query the api in a `postman` like web panel. 

### Tasks
* [x] Create white rabbit organization on `rapidapi`
* [x] Create Meow facts documentation as apart of the org
* [x] update `README.md` with new link to the rapidapi page
* [x] update org's documentation page to have a link to it as well

organization account
https://rapidapi.com/orghomepage/wh-iterabb-it

This API is listed publicly now here: 
https://rapidapi.com/wh-iterabb-it-wh-iterabb-it-default/api/meowfacts/

We link to it, and will do our best to keep the documentation in sync

**Comment by BeauBouchard** [comment]
We have an organization account listed at :
https://rapidapi.com/orghomepage/wh-iterabb-it

This API is listed publicly now here: 
https://rapidapi.com/wh-iterabb-it-wh-iterabb-it-default/api/meowfacts/

We link to it, and will do our best to keep the documentation in sync
