### ISSUE TITLE
[chore] Update Documentation for OpenAPI 3

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#280]
# Description

I want to convert the existing YAML to a JSON file, and use that going forward from our repo. 

### Tasks
* [ ] Document `/health` endpoint
* [ ] Document `/options` endpoint
* [ ] Refactor `YAML` to `JSON`
