### ISSUE TITLE
[chore] Readd CodeCov 

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#283]
Previously we let codecoverage reporting from codecov to continue to be disabled after the previous issues they had a few years ago. 
Overall I would like to have a codecoverage service still, and due to the public nature of this codebase, we want to re-enable this service and repair its integration. 

### Tasks
* [ ] Add a step to the CI/CD on Push workflow
* [ ] Add coverage badge to `README.md`
* [ ] (optional) add necessary tests if there is missing coverage
